"""Add agent config and knowledge base

Revision ID: 277ad1b4ebda
Revises: 07dc3c2e6fa3
Create Date: 2025-02-13 12:03:31.814669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277ad1b4ebda'
down_revision: Union[str, None] = '07dc3c2e6fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
