"""Updated table schema

Revision ID: cbe74bb3bd4d
Revises: f7f6d7395f38
Create Date: 2025-02-14 17:45:02.484697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbe74bb3bd4d'
down_revision: Union[str, None] = 'f7f6d7395f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
